# Final Genetic Algorithm

## Final Randomiser

In [55]:
import numpy as np

# Define the number of attack steps, attack paths, IDSs, and rules
num_attack_steps = 25
num_attack_paths = 10
num_ids = 6
num_rules = 30
sparsity = 0.2  # Adjust sparsity as needed (0.0 for dense matrix, 1.0 for empty matrix)

# Generate sparse random matrices for Ap2AS, IDS2AS, and Rule2AS_Req
Ap2AS = np.random.choice([0, 1], size=(num_attack_paths, num_attack_steps), p=[1-sparsity, sparsity])
IDS2AS = np.random.choice([0, 1], size=(num_ids, num_attack_steps), p=[1-sparsity, sparsity])
Rule2AS_Req = np.random.choice([0, 1], size=(num_rules, num_attack_steps), p=[1-sparsity, sparsity])

print("Ap2AS:")
print(Ap2AS)
print("\nIDS2AS:")
print(IDS2AS)
print("\nRule2AS_Req:")
print(Rule2AS_Req)

Ap2AS:
[[0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1]
 [0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1]]

IDS2AS:
[[0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1]
 [0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0]]

Rule2AS_Req:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0]
 [0 1 0 1 0 0 

## Initial Population Generator

In [62]:
IDS2Rule = np.zeros((num_ids, num_rules), dtype=int)
input_matrices=[]
for j in range(3):    
    for i in range(num_ids):
        num_rules_assigned = np.random.randint(0, 5)  # Random number of rules between 1 and 5
        rule_indices = np.random.choice(num_rules, num_rules_assigned, replace=False)
        IDS2Rule[i, rule_indices] = 1
    input_matrices.append(IDS2Rule)

print("Initial Population:")
print(input_matrices)

Initial Population:
[array([[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0]]), array([[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 

## Genetic Algorithm

In [65]:
import numpy as np
import pygad

capacity = [20000, 20000, 20000, 20000,20000,20000]
traffic = [10,10,10,10,10,10]
Rules_Allowed = [i // j for i, j in zip(capacity, traffic)]
ADEP = [0]
def count_non_zero_rows(matrix):
    count = 0
    for row in matrix:
        if np.sum(row) != 0:
            count += 1
    return count

# Fitness function
def fitness_func(ga_instance, solution, solution_idx):
    # Initial Matrices
    IDS2Rule = np.array(solution).reshape(rows, cols)  # Reshape the solution 
    #Ap2AS = np.array([[1,0,1,0,0,0,1,1],[1,0,0,0,1,1,0,1],[0,1,0,1,0,0,1,1]])
    #IDS2AS = [[1,0,1,0,0,0,0,0],[0,1,1,0,0,0,1,0],[0,0,0,0,1,0,1,1],[0,0,0,0,0,0,0,1]]
    #Rule2AS_Req = [[0,0,1,1,0,1,1,0],[0,1,0,0,1,0,0,0],[1,0,0,0,0,0,0,1]]
    #num_attack_steps = 8
    alpha = 1
    beta = 1
    gamma = 1
    e = 2.718
    row_sums = np.sum(IDS2Rule, axis=1)
    exceeds_limit = np.any(row_sums > Rules_Allowed) #row_sum*traffic > capacity
    if np.any(exceeds_limit):
        fitness_value = -np.inf
    else:
        #print("****FA***")
        # Calculate FA:
        fa = np.sum(Ap2AS, axis=0)
        #print(fa)
        FA = []
        #Calculating the Attack Steps observed and detected by each IDS
        Detected = []
        IDS = 0
        detected = np.zeros((num_attack_steps), dtype=int)
        for i in IDS2Rule:
            indices = np.where(i == 1)[0]
            for j in indices:
                andop = np.logical_and(IDS2AS[IDS],Rule2AS_Req[j]).astype(int)
                detected = np.logical_or(detected,andop).astype(int)      
            IDS +=1
        indices = [index for index, value in enumerate(detected) if value == 1]
        #print(indices)
        values_at_indices = [fa[index] for index in indices]
        FA = values_at_indices
        #print(FA)
        #print("****FP***")
        #Calculate FP:
        # Create a dictionary to store pairs and their frequencies
        pair_freq = {}
        # Iterate over each row of Ap2AS to count pairs
        for row in Ap2AS:
            indices = np.where(row == 1)[0]
            for i in range(len(indices)):
                for j in range(i+1, len(indices)):
                    pair = (indices[i], indices[j])
                    pair_freq[pair] = pair_freq.get(pair, 0) + 1
        #print(pair_freq)
        FP = []
        index_pairs = [(i, j) for i in range(len(detected)) for j in range(i+1, len(detected)) if detected[i] == 1 and detected[j] == 1]
        #print(index_pairs)
        for pair in index_pairs:
          if pair_freq.get(pair) != None:
            FP.append(pair_freq.get(pair))
        #print(FP)
        #print("****CUD***")
        #calculating CUD
        IDS = 0
        CUD = 0
        for i in IDS2Rule:
            indices = np.where(i == 1)[0]
            for j in indices:
                HIT = 0
                for k,m in zip(IDS2AS[IDS],Rule2AS_Req[j]):
                  if k*m == 1:
                    HIT +=1
                if HIT == 0:
                    CUD +=1       
            IDS +=1
        #print(CUD)
        #print("******FINAL*****")
        #print('FA: \n ',FA,'\nFP: \n',FP,'\nCUD: \n',CUD)
        if CUD != 0:
          fitness_value = alpha*np.sum(np.exp(FA))-beta*np.sum(np.exp(FP))-gamma*(pow(e,CUD))
        else:
          fitness_value = alpha*np.sum(np.exp(FA))-beta*np.sum(np.exp(FP))
        print(fitness_value)
    return fitness_value

# Define the dimensions of the solution matrix
rows = num_ids
cols = num_rules

# Define the Initial Population
#input_matrices = [np.array([[0, 0, 1], [0, 1, 0], [0, 0, 0], [0,0,0]]),
#                   np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0],[0,0,1]]),
#                  np.array([[0, 0, 0], [1, 0, 0], [0, 1, 0],[0,0,0]])]

# Flatten and concatenate the matrices into a single input array
#flattened_input = np.concatenate([matrix.flatten() for matrix in input_matrices])

# Set the initial population as the input matrices
ini_population = np.array([matrix.flatten() for matrix in input_matrices])

# Define the GA parameters
num_generations = 100 # Number of generations. 50 was not giving the best solution every time. 
num_parents_mating = 2 # Number of solutions to be selected as parents. 
fitness_func = fitness_func # Fitness Function

#sol_per_pop = 8 Not required if there is an initial population
#init_range_low = -2
#init_range_high = 5

parent_selection_type = "sss" #The parent selection type. sss (for steady-state selection)
keep_parents = -1 # Not keeping the parents to make the population more dynamic

# keep_parents=-1: Number of parents to keep in the current population. 
#-1 (default) means to keep all parents in the next population. 
#0 means keep no parents in the next population. 
#A value greater than 0 means keeps the specified number of parents in the next population.

crossover_type = "single_point"

mutation_type = "random" # Since our matrices are sparce, bit flip will not be a good choice
mutation_percent_genes = 10 #10% of the genes will be mutated.
#A higher values might take the solution away from initial solution. 

# Custom stopping criteria function
def custom_stopping(ga_instance):
    sols = np.array(ga_instance.solutions)
    DEP = []
    for solution in sols:
        IDS2Rule = np.array(solution).reshape(rows, cols)  # Reshape the solution 
        # Calculate Rule2AI_deploy: which traffic will pass through which rule
        Rule2AS_deploy = np.dot(np.transpose(IDS2Rule), IDS2AS)

        # Calculate Rule2AI_Detect: Which Rule actually detects which attack instance
        Rule2AS_Detect = np.logical_and(Rule2AS_deploy, Rule2AS_Req).astype(int)

        # Calculate Ap2Rule: Which Attack path stopped by which rule
        Ap2Rule = np.dot(Ap2AS, np.transpose(Rule2AS_Detect))

        dep = count_non_zero_rows(Ap2Rule)
        DEP.append(dep)
    ADEP.append(np.average(DEP))
    length = len(ADEP)
    print("ADEP: ",ADEP)
    if  abs(ADEP[length-1]-ADEP[length-2]) < 0.000001:
        return True
    else:
        return False

# Callback function for custom stopping condition
def on_generation(ga_instance):
    if custom_stopping(ga_instance):
        ga_instance.keep_solutions_history = False  # Stop recording solutions history
        return "stop"

# Create an instance of the pygad.GA class with the initial population
ga_instance = pygad.GA(num_generations=num_generations,
                       num_parents_mating=num_parents_mating,
                       fitness_func=fitness_func,
                       initial_population=ini_population,
                       gene_space=[0,1],
                       parent_selection_type=parent_selection_type,
                       keep_parents=keep_parents,
                       crossover_type=crossover_type,
                       mutation_type=mutation_type,
                       mutation_percent_genes=mutation_percent_genes,
                       #stop_criteria="saturate_10",
                       on_generation = on_generation,
                       save_solutions=True
                       )

# Running the GA to optimize the solution
ga_instance.run()
solution, solution_fitness, solution_idx = ga_instance.best_solution()
print("Parameters of the best solution")
sol= np.array(solution).reshape(rows, cols)
print(sol)
print("Fitness value of the best solution = {solution_fitness}".format(solution_fitness=solution_fitness))

-3263810.237658645
-3263810.237658645
-3263810.237658645
-3263806.7535874303
-65537436.906554595
ADEP:  [0, 10.0]
-178130914.26954353
-26423287829.815212
ADEP:  [0, 10.0, 10.0]
Parameters of the best solution
[[0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.
  0. 0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0.
  0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.
  0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0.
  0. 1. 0. 0. 1. 0.]]
Fitness value of the best solution = -3263806.7535874303


In [3]:
import numpy as np
import pygad

example = 1 # 1 means Big

if(example == 1):
  num_ids = 6
  num_rules = 30
  num_attack_steps = 25
  num_attack_paths = 10
  capacity = [20000, 20000, 20000, 20000, 20000, 20000]
  traffic = [10000, 5000, 7000, 10000, 6000, 10000]
else:
  num_ids = 4
  num_rules = 3
  num_attack_steps = 8
  num_attack_paths = 3
  capacity = [5000, 5000, 5000, 5000]
  traffic = [6000, 6000, 3000, 5000]

Rules_Allowed = [i // j for i, j in zip(capacity, traffic)]
ADEP = [0]

def count_non_zero_rows(matrix):
    count = 0
    for row in matrix:
        if np.sum(row) != 0:
            count += 1
    return count

#All the input Matrices
if(example == 1):
  Ap2AS = np.array([
                        [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0],
                        [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
                        [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
                        [0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1],
                        [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0],
                        [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
                        [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0],
                        [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]])
  IDS2AS = [
                        [1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
                        [0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0],
                        [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
                        [0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1]]
  Rule2AS_Req = [
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
                        [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
                        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
                        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
                        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]]
else:
  Ap2AS = np.array([[1,0,1,0,0,0,1,1],
                    [1,0,0,0,1,1,0,0],
                    [0,1,0,1,0,0,1,1]])
  IDS2AS = [        [1,0,1,0,0,0,0,0],
                    [0,1,1,0,0,0,1,0],
                    [0,0,0,0,1,0,1,1],
                    [0,0,0,0,0,0,0,1]]
  Rule2AS_Req = [   [0,0,1,1,0,1,1,0],
                    [0,1,0,0,1,0,0,0],
                    [1,0,0,0,0,0,0,1]]

e = 2.718


# Define the Initial Population
if(example == 1):
  # input_matrices = [np.array([[1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
  #                   np.array([[0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
  #                   np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]]),
  #                   np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]),
  #                   np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  #                             [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #                             [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])]
  IDS2Rule = np.zeros((num_ids, num_rules), dtype=int)
  input_matrices=[]
  for j in range(5):    
      for i in range(num_ids):
          num_rules_assigned = np.random.randint(0, 1)  # Random number of rules between 1 and 5
          rule_indices = np.random.choice(num_rules, num_rules_assigned, replace=False)
          IDS2Rule[i, rule_indices] = 1
      input_matrices.append(IDS2Rule)

  #print("Initial Population:")
  #print(input_matrices)

else:
  input_matrices = [np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]),
                    np.array([[0, 0, 1], [0, 1, 0], [0, 0, 0], [0, 0, 0]]),
                    np.array([[0, 0, 0], [0, 0, 1], [0, 0, 0], [0, 0, 0]]),
                    np.array([[0, 0, 0], [0, 0, 0], [0, 1, 0], [0, 0, 0]]),
                    np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0], [0, 0, 0]])]

# Fitness function
def fitness_func(ga_instance, solution, solution_idx):
    # Initial Matrices
    IDS2Rule = np.array(solution).reshape(num_ids, num_rules)  # Reshape the solution 

    row_sums = np.sum(IDS2Rule, axis=1)
    exceeds_limit = np.any(row_sums > Rules_Allowed) #row_sum*traffic > capacity
    if np.any(exceeds_limit):
        fitness_value = -np.inf
        print("ARE")
    else:
    # Calculate FA:
        fa = np.sum(Ap2AS, axis=0)
        #print(fa)
        FA = []
        #Calculating the Attack Steps observed and detected by each IDS
        Detected = []
        IDS = 0
        detected = np.zeros((num_attack_steps), dtype=int)
        for i in IDS2Rule:
            indices = np.where(i == 1)[0]
            for j in indices:
                andop = np.logical_and(IDS2AS[IDS],Rule2AS_Req[j]).astype(int)
                detected = np.logical_or(detected,andop).astype(int)      
            IDS +=1
        indices = [index for index, value in enumerate(detected) if value == 1]
        total = sum(detected)
        print("No of detections :", total)
        #print(indices)
        values_at_indices = [fa[index] for index in indices]
        FA = values_at_indices
        #print("FA : ",FA)

        #Calculate FP:
        # Create a dictionary to store pairs and their frequencies
        pair_freq = {}
        # Iterate over each row of Ap2AS to count pairs
        for row in Ap2AS:
            indices = np.where(row == 1)[0]
            for i in range(len(indices)):
                for j in range(i+1, len(indices)):
                    pair = (indices[i], indices[j])
                    pair_freq[pair] = pair_freq.get(pair, 0) + 1
        #print(pair_freq)
        FP = []
        index_pairs = [(i, j) for i in range(len(detected)) for j in range(i+1, len(detected)) if detected[i] == 1 and detected[j] == 1]
        #print(index_pairs)
        for pair in index_pairs:
          if pair_freq.get(pair) != None:
            FP.append(pair_freq.get(pair))
        #print("FP : ",FP)

        #calculating CUD
        IDS = 0
        CUD = 0
        for i in IDS2Rule:
            indices = np.where(i == 1)[0]
            for j in indices:
                HIT = 0
                for k,m in zip(IDS2AS[IDS],Rule2AS_Req[j]):
                  if k*m == 1:
                    HIT +=1
                if HIT == 0:
                    CUD +=1       
            IDS +=1
        #print("CUD : ",CUD)
        
        #print(IDS2Rule)
        
        ############################################
        ############################################
        # Calculate Rule2AI_deploy: which traffic will pass through which rule
        Rule2AS_deploy = np.dot(np.transpose(IDS2Rule), IDS2AS)
        # Calculate Rule2AI_Detect: Which Rule actually detects which attack instance
        Rule2AS_Detect = np.logical_and(Rule2AS_deploy, Rule2AS_Req).astype(int)
        # Calculate Ap2Rule: Which Attack path stopped by which rule
        Ap2Rule = np.dot(Ap2AS, np.transpose(Rule2AS_Detect))
        dep = count_non_zero_rows(Ap2Rule)
        print("DEP: ", dep)
        ###########################################
        #fitness_value = 5*(pow(e,dep)) + 10*np.sum(np.exp(FA)) - 5*np.sum(np.exp(FP)) - 1*pow(CUD, 2)
        fitness_value = (pow(e,dep)) + np.sum(np.exp(FA)) - np.sum(np.exp(FP)) - pow(CUD, 2)
        print("FIT: ", fitness_value)

    return fitness_value


# Flatten and concatenate the matrices into a single input array
#flattened_input = np.concatenate([matrix.flatten() for matrix in input_matrices])

# Set the initial population as the input matrices
ini_population = np.array([matrix.flatten() for matrix in input_matrices])


# Custom stopping criteria function
def custom_stopping(ga_instance):
    sols = np.array(ga_instance.solutions)
    DEP = []
    for solution in sols:
        IDS2Rule = np.array(solution).reshape(num_ids, num_rules)  # Reshape the solution 
        # Calculate Rule2AI_deploy: which traffic will pass through which rule
        Rule2AS_deploy = np.dot(np.transpose(IDS2Rule), IDS2AS)

        # Calculate Rule2AI_Detect: Which Rule actually detects which attack instance
        Rule2AS_Detect = np.logical_and(Rule2AS_deploy, Rule2AS_Req).astype(int)

        # Calculate Ap2Rule: Which Attack path stopped by which rule
        Ap2Rule = np.dot(Ap2AS, np.transpose(Rule2AS_Detect))

        dep = count_non_zero_rows(Ap2Rule)
        DEP.append(dep)
    ADEP.append(np.average(DEP))
    length = len(ADEP)
    print("ADEP: ",ADEP[length-1])
    if  abs(ADEP[length-1]-ADEP[length-2]) < 0.001:
        return True
    else:
        return False

# Callback function for custom stopping condition
def on_generation(ga_instance):
    for idx, fitness in enumerate(ga_instance.previous_generation_fitness):
        if np.isinf(fitness):
            #print("IDX :", idx)
            ga_instance.population[idx] = ga_instance.last_generation_elitism[len(ga_instance.last_generation_elitism)-1]
            #print(np.array(ga_instance.last_generation_elitism[0]).reshape(num_ids, num_rules))
            #ga_instance.previous_generation_fitness[idx] = np.nan
    # if custom_stopping(ga_instance):
    #     ga_instance.keep_solutions_history = False  # Stop recording solutions history
    #     return "stop"


# Create an instance of the pygad.GA class with the initial population
ga_instance = pygad.GA(num_generations=50,
                       num_parents_mating=3,
                       #sol_per_pop = 10,
                       fitness_func=fitness_func,
                       initial_population=ini_population,
                       gene_space=[0,1],
                       parent_selection_type="sss",
                       keep_elitism=2,
                       #keep_parents=-1,
                       crossover_type="single_point",
                       mutation_type="random",
                       mutation_percent_genes = 5,
                       #stop_criteria="saturate_10",
                       on_generation = on_generation,
                       save_solutions=True,
                       save_best_solutions=True
                       )

# Running the GA to optimize the solution
ga_instance.run()

#print(len(ga_instance.best_solutions))
#print(len(ga_instance.best_solutions_fitness))

for i,j in zip(ga_instance.best_solutions,ga_instance.best_solutions_fitness):
    if j == max(ga_instance.best_solutions_fitness):
        print("Best Solution and Fitness is: \n")
        print(np.array(i).reshape(num_ids, num_rules))
        print(j)
        break
#solution, solution_fitness, solution_idx = ga_instance.best_solutions()
#print("Parameters of the best solution")
#sol= np.array(solution).reshape(num_ids, num_rules)
#print(sol)
#print("Fitness value of the best solution = {solution_fitness}".format(solution_fitness=solution_fitness))


# to find DEP for the final 
IDS2Rule_fi = np.array(i).reshape(num_ids, num_rules)  # Reshape the solution 
# Calculate Rule2AI_deploy: which traffic will pass through which rule
Rule2AS_deploy_fi = np.dot(np.transpose(IDS2Rule_fi), IDS2AS)
# Calculate Rule2AI_Detect: Which Rule actually detects which attack instance
Rule2AS_Detect_fi = np.logical_and(Rule2AS_deploy_fi, Rule2AS_Req).astype(int)
# Calculate Ap2Rule: Which Attack path stopped by which rule
Ap2Rule_fi = np.dot(Ap2AS, np.transpose(Rule2AS_Detect_fi))
dep = count_non_zero_rows(Ap2Rule_fi)
print("Final DEP: ", dep)

No of detections : 0
DEP:  0
FIT:  1.0
No of detections : 0
DEP:  0
FIT:  1.0
No of detections : 0
DEP:  0
FIT:  1.0
No of detections : 0
DEP:  0
FIT:  1.0
No of detections : 0
DEP:  0
FIT:  1.0
ARE
No of detections : 5
DEP:  10
FIT:  22285.65267117634
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
No of detections : 3
DEP:  5
FIT:  121.78903050978187
ARE
ARE
ARE
ARE
ARE
ARE
ARE
No of detections : 1
DEP:  1
FIT:  -58.563718171540955
ARE
ARE
No of detections : 6
DEP:  10
FIT:  22152.783413658068
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
ARE
Bes